package graphics;

public enum Texture {
    PIG,
    MAIN_LOGO,
    MENU_BACKGROUND,
    MAIN_LOGO_FLASH_0,
    MAIN_LOGO_FLASH_1,
    MAIN_LOGO_FLASH_2,
    MAIN_LOGO_FLASH_3,
    MAIN_LOGO_FLASH_4,
    MAIN_LOGO_FLASH_5,
    MAIN_LOGO_FLASH_6,
    MAIN_LOGO_FLASH_7,
    MAIN_LOGO_FLASH_8,
    MAIN_LOGO_FLASH_9,
    MAIN_LOGO_FLASH_10;
}
